services:
  fmd2:
    image: ghcr.io/yukariin/fmd2:latest
    container_name: fmd2
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - UMASK=022
      - THRESHOLD_MINUTES=3
      - TRANSFER_FILE_TYPE=.cbz
    ports:
      - 3000:3000
    volumes:
      - ./fmd:/app/FMD2/userdata
      - ./manga:/downloads
    restart: unless-stopped
